"2014-04-24 21:33:24 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 21:33:24.339630
Variable name: rty
Site name: erty
TTY port: /dev/currentcost
"
"2014-04-24 21:33:24 - messager.py - send - ERROR - {"variableID": "rty", "dstTimezone": "CEST", "siteID": "erty", "date": "2014-04-24T19:33:24.340112", "message": "CurrentCost rty in erty: TTY connection problem: /dev/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-24 21:33:29 - messager.py - send - ERROR - {"variableID": "rty", "dstTimezone": "CEST", "siteID": "erty", "date": "2014-04-24T19:33:29.344742", "message": "CurrentCost rty in erty: TTY connection problem: /dev/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-24 21:33:34 - messager.py - send - ERROR - {"variableID": "rty", "dstTimezone": "CEST", "siteID": "erty", "date": "2014-04-24T19:33:34.345340", "message": "CurrentCost rty in erty: TTY connection problem: /dev/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-24 21:59:16 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 21:59:16.304549
Variable name: rtyu
Site name: rtyui
TTY port: /dev/currentcost
"
"2014-04-24 22:31:36 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: EDzadminZE, password: pasZECZCordZE, host: localhost"
"2014-04-24 22:31:36 - messager.py - send - ERROR - It works!"
"2014-04-24 22:31:36 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T20:31:36.963138", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-24 22:31:36 - messager.py - __init__ - ERROR - Problem trying to connect to RabbitMQ with this configuration: username: admin, password: password, host: 192.168.5.56"
"2014-04-24 22:31:36 - messager.py - send - ERROR - It works!"
"2014-04-24 22:31:36 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T20:31:36.986443", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-24 22:31:37 - messager.py - send - ERROR - It works!"
"2014-04-24 22:31:37 - messager.py - send - ERROR - It works!"
"2014-04-24 22:31:37 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T20:31:37.066060", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-24 22:31:38 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 22:31:38.299092
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-24 22:31:38 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T20:31:38.299863", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-24 22:31:43 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 22:31:43.327868
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-24 22:31:46 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: admzfzein, password: paszeasword, host: localhost"
"2014-04-24 22:31:46 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T20:31:46.332932", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-24 22:31:48 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 22:31:48.332964
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-24 22:31:48 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T20:31:48.351175", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-24 22:31:49 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 22:31:49.422112
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-24 22:31:49 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-24 22:31:59 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T20:31:59.450472", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Reach timeout. Verify CurrentCost wire connection or wave range", "nonDstTimezone": "CET"}"
"2014-04-24 22:31:59 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 22:31:59.664741
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-24 22:31:59 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-24 22:32:02 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: TTY port tests/tty/currentcost disconnected."
"2014-04-24 22:32:02 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T20:32:02.499472", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: tests/tty/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-24 22:32:03 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 22:32:03.741599
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-24 22:32:03 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-24 22:32:04 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T20:32:04.577757", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Send incorrect message => <msg><src>ensor>0</sensor><id>00077</id><type>1</type><ch1><watts>00405</watts></ch1></msg>.", "nonDstTimezone": "CET"}"
"2014-04-24 22:32:06 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 22:32:06.827119
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-24 22:32:06 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-24 22:32:07 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T20:32:07.654515", "message": "<msg><src>CC128-v1.29</src><dsb>00786</dsb><time>00:31:36</time><tmpr>19.3</tmpr><sensor>0</sensor><id>00077</id><type>1</type><ch1><watts>00405</watts></ch1></msg>", "nonDstTimezone": "CET"}"
"2014-04-24 22:34:43 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: EDzadminZE, password: pasZECZCordZE, host: localhost"
"2014-04-24 22:34:43 - messager.py - send - ERROR - It works!"
"2014-04-24 22:34:43 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T20:34:43.593191", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-24 22:34:43 - messager.py - __init__ - ERROR - Problem trying to connect to RabbitMQ with this configuration: username: admin, password: password, host: 192.168.5.56"
"2014-04-24 22:34:43 - messager.py - send - ERROR - It works!"
"2014-04-24 22:34:43 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T20:34:43.845788", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-24 22:34:43 - messager.py - send - ERROR - It works!"
"2014-04-24 22:34:43 - messager.py - send - ERROR - It works!"
"2014-04-24 22:34:43 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T20:34:43.923828", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-24 22:34:45 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 22:34:45.250926
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-24 22:34:45 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T20:34:45.251388", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-24 22:34:50 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 22:34:50.251333
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-24 22:34:53 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: admzfzein, password: paszeasword, host: localhost"
"2014-04-24 22:34:53 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T20:34:53.256698", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-24 22:34:55 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 22:34:55.255985
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-24 22:34:55 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T20:34:55.274243", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-24 22:34:56 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 22:34:56.315161
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-24 22:34:56 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-24 22:35:06 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T20:35:06.333623", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Reach timeout. Verify CurrentCost wire connection or wave range", "nonDstTimezone": "CET"}"
"2014-04-24 22:35:06 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 22:35:06.547935
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-24 22:35:06 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-24 22:35:09 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: TTY port tests/tty/currentcost disconnected."
"2014-04-24 22:35:09 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T20:35:09.382718", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: tests/tty/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-24 22:35:10 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 22:35:10.644258
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-24 22:35:10 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-24 22:35:11 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T20:35:11.463183", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Send incorrect message => <msg><src>ensor>0</sensor><id>00077</id><type>1</type><ch1><watts>00405</watts></ch1></msg>.", "nonDstTimezone": "CET"}"
"2014-04-24 22:35:13 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 22:35:13.726389
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-24 22:35:13 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-24 22:35:14 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T20:35:14.534935", "message": "<msg><src>CC128-v1.29</src><dsb>00786</dsb><time>00:31:36</time><tmpr>19.3</tmpr><sensor>0</sensor><id>00077</id><type>1</type><ch1><watts>00405</watts></ch1></msg>", "nonDstTimezone": "CET"}"
"2014-04-24 22:56:01 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: EDzadminZE, password: pasZECZCordZE, host: localhost"
"2014-04-24 22:56:01 - messager.py - send - ERROR - It works!"
"2014-04-24 22:56:01 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T20:56:01.527398", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-24 22:56:01 - messager.py - __init__ - ERROR - Problem trying to connect to RabbitMQ with this configuration: username: admin, password: password, host: 192.168.5.56"
"2014-04-24 22:56:01 - messager.py - send - ERROR - It works!"
"2014-04-24 22:56:01 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T20:56:01.780300", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-24 22:56:01 - messager.py - send - ERROR - It works!"
"2014-04-24 22:56:01 - messager.py - send - ERROR - It works!"
"2014-04-24 22:56:01 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T20:56:01.859238", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-24 22:56:03 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 22:56:03.303469
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-24 22:56:03 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T20:56:03.304198", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-24 22:56:08 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 22:56:08.341732
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-24 22:56:11 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: admzfzein, password: paszeasword, host: localhost"
"2014-04-24 22:56:11 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T20:56:11.346732", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-24 22:56:13 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 22:56:13.339893
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-24 22:56:13 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T20:56:13.358955", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-24 22:56:14 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 22:56:14.410423
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-24 22:56:14 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-24 22:56:24 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T20:56:24.429608", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Reach timeout. Verify CurrentCost wire connection or wave range", "nonDstTimezone": "CET"}"
"2014-04-24 22:56:24 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 22:56:24.650091
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-24 22:56:24 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-24 22:56:27 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: TTY port tests/tty/currentcost disconnected."
"2014-04-24 22:56:27 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T20:56:27.478147", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: tests/tty/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-24 22:56:28 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 22:56:28.728581
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-24 22:56:28 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-24 22:56:29 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T20:56:29.557981", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Send incorrect message => <msg><src>ensor>0</sensor><id>00077</id><type>1</type><ch1><watts>00405</watts></ch1></msg>.", "nonDstTimezone": "CET"}"
"2014-04-24 22:56:31 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 22:56:31.810248
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-24 22:56:31 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-24 22:56:32 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T20:56:32.632534", "message": "<msg><src>CC128-v1.29</src><dsb>00786</dsb><time>00:31:36</time><tmpr>19.3</tmpr><sensor>0</sensor><id>00077</id><type>1</type><ch1><watts>00405</watts></ch1></msg>", "nonDstTimezone": "CET"}"
"2014-04-24 23:29:12 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: EDzadminZE, password: pasZECZCordZE, host: localhost"
"2014-04-24 23:29:12 - messager.py - send - ERROR - It works!"
"2014-04-24 23:29:12 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T21:29:12.170263", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-24 23:29:12 - messager.py - __init__ - ERROR - Problem trying to connect to RabbitMQ with this configuration: username: admin, password: password, host: 192.168.5.56"
"2014-04-24 23:29:12 - messager.py - send - ERROR - It works!"
"2014-04-24 23:29:12 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T21:29:12.193909", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-24 23:29:12 - messager.py - send - ERROR - It works!"
"2014-04-24 23:29:12 - messager.py - send - ERROR - It works!"
"2014-04-24 23:29:12 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T21:29:12.274885", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-24 23:29:13 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 23:29:13.622503
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-24 23:29:13 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T21:29:13.623206", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-24 23:29:18 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 23:29:18.618688
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-24 23:29:21 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: admzfzein, password: paszeasword, host: localhost"
"2014-04-24 23:29:21 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T21:29:21.623785", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-24 23:29:23 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 23:29:23.646313
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-24 23:29:23 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T21:29:23.666285", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-24 23:29:24 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 23:29:24.697871
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-24 23:29:24 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-24 23:29:34 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T21:29:34.725899", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Reach timeout. Verify CurrentCost wire connection or wave range", "nonDstTimezone": "CET"}"
"2014-04-24 23:29:34 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 23:29:34.943486
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-24 23:29:34 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-24 23:29:37 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: TTY port tests/tty/currentcost disconnected."
"2014-04-24 23:29:37 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T21:29:37.776381", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: tests/tty/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-24 23:29:39 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 23:29:39.034995
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-24 23:29:39 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-24 23:29:39 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T21:29:39.847652", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Send incorrect message => <msg><src>ensor>0</sensor><id>00077</id><type>1</type><ch1><watts>00405</watts></ch1></msg>.", "nonDstTimezone": "CET"}"
"2014-04-24 23:29:42 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 23:29:42.087356
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-24 23:29:42 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-24 23:29:42 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T21:29:42.923996", "message": "<msg><src>CC128-v1.29</src><dsb>00786</dsb><time>00:31:36</time><tmpr>19.3</tmpr><sensor>0</sensor><id>00077</id><type>1</type><ch1><watts>00405</watts></ch1></msg>", "nonDstTimezone": "CET"}"
"2014-04-25 00:14:19 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: EDzadminZE, password: pasZECZCordZE, host: localhost"
"2014-04-25 00:14:19 - messager.py - send - ERROR - It works!"
"2014-04-25 00:14:19 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T22:14:19.814353", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 00:14:19 - messager.py - __init__ - ERROR - Problem trying to connect to RabbitMQ with this configuration: username: admin, password: password, host: 192.168.5.56"
"2014-04-25 00:14:19 - messager.py - send - ERROR - It works!"
"2014-04-25 00:14:19 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T22:14:19.837127", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 00:14:19 - messager.py - send - ERROR - It works!"
"2014-04-25 00:14:19 - messager.py - send - ERROR - It works!"
"2014-04-25 00:14:19 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T22:14:19.917000", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 00:16:52 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: EDzadminZE, password: pasZECZCordZE, host: localhost"
"2014-04-25 00:16:52 - messager.py - send - ERROR - It works!"
"2014-04-25 00:16:52 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T22:16:52.769753", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 00:16:53 - messager.py - __init__ - ERROR - Problem trying to connect to RabbitMQ with this configuration: username: admin, password: password, host: 192.168.5.56"
"2014-04-25 00:16:53 - messager.py - send - ERROR - It works!"
"2014-04-25 00:16:53 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T22:16:53.022675", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 00:16:53 - messager.py - send - ERROR - It works!"
"2014-04-25 00:16:53 - messager.py - send - ERROR - It works!"
"2014-04-25 00:16:53 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T22:16:53.102886", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 00:16:54 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 00:16:54.362495
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-25 00:16:54 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T22:16:54.362980", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 00:16:59 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 00:16:59.384685
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-25 00:17:02 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: admzfzein, password: paszeasword, host: localhost"
"2014-04-25 00:17:02 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T22:17:02.397716", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 00:17:04 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 00:17:04.401860
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-25 00:17:04 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T22:17:04.422713", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 00:17:05 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 00:17:05.543107
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-25 00:17:05 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-25 00:17:15 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T22:17:15.568927", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Reach timeout. Verify CurrentCost wire connection or wave range", "nonDstTimezone": "CET"}"
"2014-04-25 00:17:15 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 00:17:15.790578
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-25 00:17:15 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-25 00:17:18 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: TTY port tests/tty/currentcost disconnected."
"2014-04-25 00:17:18 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T22:17:18.619330", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: tests/tty/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 00:17:19 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 00:17:19.870392
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-25 00:17:19 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-25 00:17:20 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T22:17:20.700147", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Send incorrect message => <msg><src>ensor>0</sensor><id>00077</id><type>1</type><ch1><watts>00405</watts></ch1></msg>.", "nonDstTimezone": "CET"}"
"2014-04-25 00:17:22 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 00:17:22.962564
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-25 00:17:22 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-25 00:17:23 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T22:17:23.777324", "message": "<msg><src>CC128-v1.29</src><dsb>00786</dsb><time>00:31:36</time><tmpr>19.3</tmpr><sensor>0</sensor><id>00077</id><type>1</type><ch1><watts>00405</watts></ch1></msg>", "nonDstTimezone": "CET"}"
"2014-04-25 00:23:19 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: EDzadminZE, password: pasZECZCordZE, host: localhost"
"2014-04-25 00:23:19 - messager.py - send - ERROR - It works!"
"2014-04-25 00:23:19 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T22:23:19.462213", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 00:23:19 - messager.py - __init__ - ERROR - Problem trying to connect to RabbitMQ with this configuration: username: admin, password: password, host: 192.168.5.56"
"2014-04-25 00:23:19 - messager.py - send - ERROR - It works!"
"2014-04-25 00:23:19 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T22:23:19.485457", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 00:23:19 - messager.py - send - ERROR - It works!"
"2014-04-25 00:23:19 - messager.py - send - ERROR - It works!"
"2014-04-25 00:23:19 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T22:23:19.572171", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 00:23:20 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 00:23:20.848978
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-25 00:23:20 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T22:23:20.849606", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 00:23:25 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 00:23:25.862428
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-25 00:23:28 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: admzfzein, password: paszeasword, host: localhost"
"2014-04-25 00:23:28 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T22:23:28.867711", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 00:23:30 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 00:23:30.877642
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-25 00:23:30 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T22:23:30.897016", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 00:23:31 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 00:23:31.973684
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-25 00:23:31 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-25 00:23:42 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T22:23:42.002278", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Reach timeout. Verify CurrentCost wire connection or wave range", "nonDstTimezone": "CET"}"
"2014-04-25 00:23:42 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 00:23:42.332966
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-25 00:23:42 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-25 00:23:45 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: TTY port tests/tty/currentcost disconnected."
"2014-04-25 00:23:45 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T22:23:45.059696", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: tests/tty/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 00:23:46 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 00:23:46.323153
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-25 00:23:46 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-25 00:23:47 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T22:23:47.154057", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Send incorrect message => <msg><src>ensor>0</sensor><id>00077</id><type>1</type><ch1><watts>00405</watts></ch1></msg>.", "nonDstTimezone": "CET"}"
"2014-04-25 00:23:49 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 00:23:49.407716
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-25 00:23:49 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-25 00:23:50 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T22:23:50.240307", "message": "<msg><src>CC128-v1.29</src><dsb>00786</dsb><time>00:31:36</time><tmpr>19.3</tmpr><sensor>0</sensor><id>00077</id><type>1</type><ch1><watts>00405</watts></ch1></msg>", "nonDstTimezone": "CET"}"
"2014-04-25 00:38:57 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: EDzadminZE, password: pasZECZCordZE, host: localhost"
"2014-04-25 00:38:57 - messager.py - send - ERROR - It works!"
"2014-04-25 00:38:57 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T22:38:57.377433", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 00:38:57 - messager.py - __init__ - ERROR - Problem trying to connect to RabbitMQ with this configuration: username: admin, password: password, host: 192.168.5.56"
"2014-04-25 00:38:57 - messager.py - send - ERROR - It works!"
"2014-04-25 00:38:57 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T22:38:57.630102", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 00:38:57 - messager.py - send - ERROR - It works!"
"2014-04-25 00:38:57 - messager.py - send - ERROR - It works!"
"2014-04-25 00:38:57 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T22:38:57.708449", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 00:39:35 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: EDzadminZE, password: pasZECZCordZE, host: localhost"
"2014-04-25 00:39:35 - messager.py - send - ERROR - It works!"
"2014-04-25 00:39:35 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T22:39:35.949326", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 00:39:35 - messager.py - __init__ - ERROR - Problem trying to connect to RabbitMQ with this configuration: username: admin, password: password, host: 192.168.5.56"
"2014-04-25 00:39:35 - messager.py - send - ERROR - It works!"
"2014-04-25 00:39:35 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T22:39:35.972026", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 00:39:35 - messager.py - send - ERROR - It works!"
"2014-04-25 00:39:36 - messager.py - send - ERROR - It works!"
"2014-04-25 00:39:36 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T22:39:36.052342", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 00:39:37 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 00:39:37.297085
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-25 00:39:37 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T22:39:37.297871", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 00:39:42 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 00:39:42.331104
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-25 00:39:45 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: admzfzein, password: paszeasword, host: localhost"
"2014-04-25 00:39:45 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T22:39:45.336933", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 00:39:47 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 00:39:47.334043
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-25 00:39:47 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T22:39:47.352333", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 00:39:48 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 00:39:48.440541
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-25 00:39:48 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-25 00:39:58 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T22:39:58.465647", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Reach timeout. Verify CurrentCost wire connection or wave range", "nonDstTimezone": "CET"}"
"2014-04-25 00:39:58 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 00:39:58.681994
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-25 00:39:58 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-25 00:40:01 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: TTY port tests/tty/currentcost disconnected."
"2014-04-25 00:40:01 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T22:40:01.513522", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: tests/tty/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 00:40:02 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 00:40:02.773058
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-25 00:40:02 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-25 00:40:03 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T22:40:03.592650", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Send incorrect message => <msg><src>ensor>0</sensor><id>00077</id><type>1</type><ch1><watts>00405</watts></ch1></msg>.", "nonDstTimezone": "CET"}"
"2014-04-25 00:40:05 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 00:40:05.871592
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-25 00:40:05 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-25 00:40:06 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T22:40:06.672462", "message": "<msg><src>CC128-v1.29</src><dsb>00786</dsb><time>00:31:36</time><tmpr>19.3</tmpr><sensor>0</sensor><id>00077</id><type>1</type><ch1><watts>00405</watts></ch1></msg>", "nonDstTimezone": "CET"}"
"2014-04-25 15:40:48 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: EDzadminZE, password: pasZECZCordZE, host: localhost"
"2014-04-25 15:40:48 - messager.py - send - ERROR - It works!"
"2014-04-25 15:40:48 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-25T13:40:48.958178", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 15:40:48 - messager.py - __init__ - ERROR - Problem trying to connect to RabbitMQ with this configuration: username: admin, password: password, host: 192.168.5.56"
"2014-04-25 15:40:48 - messager.py - send - ERROR - It works!"
"2014-04-25 15:40:48 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-25T13:40:48.982752", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 15:40:49 - messager.py - send - ERROR - It works!"
"2014-04-25 15:40:49 - messager.py - send - ERROR - It works!"
"2014-04-25 15:40:49 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-25T13:40:49.246394", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 15:41:42 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: EDzadminZE, password: pasZECZCordZE, host: localhost"
"2014-04-25 15:41:42 - messager.py - send - ERROR - It works!"
"2014-04-25 15:41:42 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-25T13:41:42.615165", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 15:41:42 - messager.py - __init__ - ERROR - Problem trying to connect to RabbitMQ with this configuration: username: admin, password: password, host: 192.168.5.56"
"2014-04-25 15:41:42 - messager.py - send - ERROR - It works!"
"2014-04-25 15:41:42 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-25T13:41:42.867711", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 15:41:42 - messager.py - send - ERROR - It works!"
"2014-04-25 15:41:42 - messager.py - send - ERROR - It works!"
"2014-04-25 15:41:42 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-25T13:41:42.948304", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 15:41:44 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 15:41:44.302618
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-25 15:41:44 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T13:41:44.303387", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 15:41:49 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 15:41:49.322894
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-25 15:41:52 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: admzfzein, password: paszeasword, host: localhost"
"2014-04-25 15:41:52 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T13:41:52.328715", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 15:41:54 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 15:41:54.323496
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-25 15:41:54 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T13:41:54.343586", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 15:41:55 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 15:41:55.749279
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-25 15:41:55 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 15:41:55.772707
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-25 15:41:55 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-25 15:41:55 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-25 15:41:58 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: TTY port tests/tty/currentcost disconnected."
"2014-04-25 15:41:58 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T13:41:58.423452", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: tests/tty/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 15:41:58 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: TTY port tests/tty/currentcost disconnected."
"2014-04-25 15:41:58 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T13:41:58.430924", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: tests/tty/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 15:41:59 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 15:41:59.611143
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-25 15:41:59 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-25 15:42:00 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T13:42:00.442241", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Send incorrect message => <msg><src>ensor>0</sensor><id>00077</id><type>1</type><ch1><watts>00405</watts></ch1></msg>.", "nonDstTimezone": "CET"}"
"2014-04-25 15:42:03 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T13:42:03.437217", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: tests/tty/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 15:42:03 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T13:42:03.451678", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: tests/tty/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 15:42:08 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T13:42:08.453987", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: tests/tty/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 15:42:08 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T13:42:08.467925", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: tests/tty/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 15:42:13 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T13:42:13.471063", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: tests/tty/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 15:42:13 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T13:42:13.482967", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: tests/tty/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 15:42:18 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T13:42:18.486835", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: tests/tty/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 15:42:18 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T13:42:18.498068", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: tests/tty/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 15:42:23 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T13:42:23.504188", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: tests/tty/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 15:42:23 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T13:42:23.514519", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: tests/tty/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 15:42:28 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-25 15:42:28 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-25 15:42:29 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 15:42:29.608792
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-25 15:42:29 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-25 15:42:30 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T13:42:30.453491", "message": "<msg><src>CC128-v1.29</src><dsb>00786</dsb><time>00:31:36</time><tmpr>19.3</tmpr><sensor>0</sensor><id>00077</id><type>1</type><ch1><watts>00405</watts></ch1></msg>", "nonDstTimezone": "CET"}"
"2014-04-25 15:42:38 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T13:42:38.530841", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Reach timeout. Verify CurrentCost wire connection or wave range", "nonDstTimezone": "CET"}"
"2014-04-25 15:42:39 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T13:42:39.637947", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Reach timeout. Verify CurrentCost wire connection or wave range", "nonDstTimezone": "CET"}"
"2014-04-25 15:42:40 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T13:42:40.476295", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Reach timeout. Verify CurrentCost wire connection or wave range", "nonDstTimezone": "CET"}"
"2014-04-25 15:42:48 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T13:42:48.550978", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Reach timeout. Verify CurrentCost wire connection or wave range", "nonDstTimezone": "CET"}"
"2014-04-25 15:42:49 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T13:42:49.659584", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Reach timeout. Verify CurrentCost wire connection or wave range", "nonDstTimezone": "CET"}"
"2014-04-25 15:42:50 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T13:42:50.498442", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Reach timeout. Verify CurrentCost wire connection or wave range", "nonDstTimezone": "CET"}"
"2014-04-25 15:42:58 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T13:42:58.570996", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Reach timeout. Verify CurrentCost wire connection or wave range", "nonDstTimezone": "CET"}"
"2014-04-25 15:42:59 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T13:42:59.681912", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Reach timeout. Verify CurrentCost wire connection or wave range", "nonDstTimezone": "CET"}"
"2014-04-25 15:43:00 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T13:43:00.520097", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Reach timeout. Verify CurrentCost wire connection or wave range", "nonDstTimezone": "CET"}"
"2014-04-25 15:43:08 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T13:43:08.592759", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Reach timeout. Verify CurrentCost wire connection or wave range", "nonDstTimezone": "CET"}"
"2014-04-25 15:43:09 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T13:43:09.703945", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Reach timeout. Verify CurrentCost wire connection or wave range", "nonDstTimezone": "CET"}"
"2014-04-25 15:43:10 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T13:43:10.542145", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Reach timeout. Verify CurrentCost wire connection or wave range", "nonDstTimezone": "CET"}"
"2014-04-25 15:43:18 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T13:43:18.615142", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Reach timeout. Verify CurrentCost wire connection or wave range", "nonDstTimezone": "CET"}"
"2014-04-25 15:43:54 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: EDzadminZE, password: pasZECZCordZE, host: localhost"
"2014-04-25 15:43:54 - messager.py - send - ERROR - It works!"
"2014-04-25 15:43:54 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-25T13:43:54.493218", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 15:43:54 - messager.py - __init__ - ERROR - Problem trying to connect to RabbitMQ with this configuration: username: admin, password: password, host: 192.168.5.56"
"2014-04-25 15:43:54 - messager.py - send - ERROR - It works!"
"2014-04-25 15:43:54 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-25T13:43:54.746314", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 15:43:54 - messager.py - send - ERROR - It works!"
"2014-04-25 15:43:54 - messager.py - send - ERROR - It works!"
"2014-04-25 15:43:54 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-25T13:43:54.826202", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 15:43:56 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 15:43:56.110164
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-25 15:43:56 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T13:43:56.110636", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 15:44:01 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 15:44:01.137206
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-25 15:44:04 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: admzfzein, password: paszeasword, host: localhost"
"2014-04-25 15:44:04 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T13:44:04.142722", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 15:44:06 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 15:44:06.156605
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-25 15:44:06 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T13:44:06.174873", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 15:44:07 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 15:44:07.226003
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-25 15:44:07 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-25 15:44:17 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T13:44:17.255037", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Reach timeout. Verify CurrentCost wire connection or wave range", "nonDstTimezone": "CET"}"
"2014-04-25 15:44:17 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 15:44:17.475925
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-25 15:44:17 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-25 15:44:20 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: TTY port tests/tty/currentcost disconnected."
"2014-04-25 15:44:20 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T13:44:20.308343", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: tests/tty/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 15:44:21 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 15:44:21.572064
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-25 15:44:21 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-25 15:44:22 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T13:44:22.385261", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Send incorrect message => <msg><src>ensor>0</sensor><id>00077</id><type>1</type><ch1><watts>00405</watts></ch1></msg>.", "nonDstTimezone": "CET"}"
"2014-04-25 15:44:24 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 15:44:24.635609
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-25 15:44:24 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-25 15:44:25 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T13:44:25.459037", "message": "<msg><src>CC128-v1.29</src><dsb>00786</dsb><time>00:31:36</time><tmpr>19.3</tmpr><sensor>0</sensor><id>00077</id><type>1</type><ch1><watts>00405</watts></ch1></msg>", "nonDstTimezone": "CET"}"
"2014-04-25 16:01:49 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: EDzadminZE, password: pasZECZCordZE, host: localhost"
"2014-04-25 16:01:49 - messager.py - send - ERROR - It works!"
"2014-04-25 16:01:49 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-25T14:01:49.639156", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 16:01:49 - messager.py - __init__ - ERROR - Problem trying to connect to RabbitMQ with this configuration: username: admin, password: password, host: 192.168.5.56"
"2014-04-25 16:01:49 - messager.py - send - ERROR - It works!"
"2014-04-25 16:01:49 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-25T14:01:49.891539", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 16:01:49 - messager.py - send - ERROR - It works!"
"2014-04-25 16:01:49 - messager.py - send - ERROR - It works!"
"2014-04-25 16:01:49 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-25T14:01:49.969585", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 16:05:51 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: EDzadminZE, password: pasZECZCordZE, host: localhost"
"2014-04-25 16:05:51 - messager.py - send - ERROR - It works!"
"2014-04-25 16:05:51 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-25T14:05:51.791180", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 16:05:52 - messager.py - __init__ - ERROR - Problem trying to connect to RabbitMQ with this configuration: username: admin, password: password, host: 192.168.5.56"
"2014-04-25 16:05:52 - messager.py - send - ERROR - It works!"
"2014-04-25 16:05:52 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-25T14:05:52.043940", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 16:05:52 - messager.py - send - ERROR - It works!"
"2014-04-25 16:05:52 - messager.py - send - ERROR - It works!"
"2014-04-25 16:05:52 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-25T14:05:52.123139", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 16:05:53 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 16:05:53.528909
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-25 16:05:53 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T14:05:53.529357", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 16:05:58 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 16:05:58.550626
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-25 16:06:01 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: admzfzein, password: paszeasword, host: localhost"
"2014-04-25 16:06:01 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T14:06:01.555721", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 16:06:03 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 16:06:03.562919
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-25 16:06:03 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T14:06:03.590666", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 16:06:04 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 16:06:04.626884
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-25 16:06:04 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-25 16:06:14 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T14:06:14.655188", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Reach timeout. Verify CurrentCost wire connection or wave range", "nonDstTimezone": "CET"}"
"2014-04-25 16:06:14 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 16:06:14.905274
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-25 16:06:14 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-25 16:06:17 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: TTY port tests/tty/currentcost disconnected."
"2014-04-25 16:06:17 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T14:06:17.704795", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: tests/tty/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 16:06:18 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 16:06:18.963365
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-25 16:06:18 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-25 16:06:19 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T14:06:19.788784", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Send incorrect message => <msg><src>ensor>0</sensor><id>00077</id><type>1</type><ch1><watts>00405</watts></ch1></msg>.", "nonDstTimezone": "CET"}"
"2014-04-25 16:06:22 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 16:06:22.035013
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-25 16:06:22 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-25 16:06:22 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T14:06:22.866189", "message": "<msg><src>CC128-v1.29</src><dsb>00786</dsb><time>00:31:36</time><tmpr>19.3</tmpr><sensor>0</sensor><id>00077</id><type>1</type><ch1><watts>00405</watts></ch1></msg>", "nonDstTimezone": "CET"}"
"2014-04-25 16:10:45 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: EDzadminZE, password: pasZECZCordZE, host: localhost"
"2014-04-25 16:10:45 - messager.py - send - ERROR - It works!"
"2014-04-25 16:10:45 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-25T14:10:45.525297", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 16:10:45 - messager.py - __init__ - ERROR - Problem trying to connect to RabbitMQ with this configuration: username: admin, password: password, host: 192.168.5.56"
"2014-04-25 16:10:45 - messager.py - send - ERROR - It works!"
"2014-04-25 16:10:45 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-25T14:10:45.549660", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 16:10:45 - messager.py - send - ERROR - It works!"
"2014-04-25 16:10:45 - messager.py - send - ERROR - It works!"
"2014-04-25 16:10:45 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-25T14:10:45.628272", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 16:10:47 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 16:10:47.000832
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-25 16:10:47 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T14:10:47.001772", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 16:10:52 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 16:10:52.017588
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-25 16:10:55 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: admzfzein, password: paszeasword, host: localhost"
"2014-04-25 16:10:55 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T14:10:55.022893", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 16:10:57 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 16:10:57.025466
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-25 16:10:57 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T14:10:57.043395", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 16:10:58 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 16:10:58.127893
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-25 16:10:58 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-25 16:11:08 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T14:11:08.155318", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Reach timeout. Verify CurrentCost wire connection or wave range", "nonDstTimezone": "CET"}"
"2014-04-25 16:11:08 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 16:11:08.397055
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-25 16:11:08 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-25 16:11:11 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: TTY port tests/tty/currentcost disconnected."
"2014-04-25 16:11:11 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T14:11:11.216913", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: tests/tty/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 16:11:12 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 16:11:12.463482
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-25 16:11:12 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-25 16:11:13 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T14:11:13.294397", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Send incorrect message => <msg><src>ensor>0</sensor><id>00077</id><type>1</type><ch1><watts>00405</watts></ch1></msg>.", "nonDstTimezone": "CET"}"
"2014-04-25 16:11:15 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 16:11:15.536655
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-25 16:11:15 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-25 16:11:16 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-25T14:11:16.369008", "message": "<msg><src>CC128-v1.29</src><dsb>00786</dsb><time>00:31:36</time><tmpr>19.3</tmpr><sensor>0</sensor><id>00077</id><type>1</type><ch1><watts>00405</watts></ch1></msg>", "nonDstTimezone": "CET"}"
"2014-04-26 19:33:32 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: EDzadminZE, password: pasZECZCordZE, host: localhost"
"2014-04-26 19:33:32 - messager.py - send - ERROR - It works!"
"2014-04-26 19:33:32 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-26T17:33:32.036148", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-26 19:33:32 - messager.py - __init__ - ERROR - Problem trying to connect to RabbitMQ with this configuration: username: admin, password: password, host: 192.168.5.56"
"2014-04-26 19:33:32 - messager.py - send - ERROR - It works!"
"2014-04-26 19:33:32 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-26T17:33:32.288548", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-26 19:33:32 - messager.py - send - ERROR - It works!"
"2014-04-26 19:33:32 - messager.py - send - ERROR - It works!"
"2014-04-26 19:33:32 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-26T17:33:32.367860", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-26 19:33:33 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-26 19:33:33.707518
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
Log configuration: logs/log.conf
"
"2014-04-26 19:33:33 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-26T17:33:33.707982", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-26 19:33:38 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-26 19:33:38.728337
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
Log configuration: logs/log.conf
"
"2014-04-26 19:33:41 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: admzfzein, password: paszeasword, host: localhost"
"2014-04-26 19:33:41 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-26T17:33:41.733704", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-26 19:33:43 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-26 19:33:43.728826
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
Log configuration: logs/log.conf
"
"2014-04-26 19:33:43 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-26T17:33:43.747171", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-26 19:33:45 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-26 19:33:45.006918
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
Log configuration: logs/log.conf
"
"2014-04-26 19:33:45 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-26 19:33:45.023370
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
Log configuration: logs/log.conf
"
"2014-04-26 19:33:45 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-26 19:33:45 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-26 19:33:47 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: TTY port tests/tty/currentcost disconnected."
"2014-04-26 19:33:47 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-26T17:33:47.754260", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: tests/tty/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-26 19:33:47 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: TTY port tests/tty/currentcost disconnected."
"2014-04-26 19:33:47 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-26T17:33:47.755579", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: tests/tty/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-26 19:33:48 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-26 19:33:48.949591
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
Log configuration: logs/log.conf
"
"2014-04-26 19:33:48 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-26 19:33:49 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-26T17:33:49.774443", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Send incorrect message => <msg><src>ensor>0</sensor><id>00077</id><type>1</type><ch1><watts>00405</watts></ch1></msg>.", "nonDstTimezone": "CET"}"
"2014-04-26 19:33:52 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-26T17:33:52.774047", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: tests/tty/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-26 19:33:52 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-26T17:33:52.774948", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: tests/tty/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-26 19:33:57 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-26T17:33:57.788178", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: tests/tty/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-26 19:33:57 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-26T17:33:57.791906", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: tests/tty/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-26 19:34:02 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-26T17:34:02.803379", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: tests/tty/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-26 19:34:02 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-26T17:34:02.806018", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: tests/tty/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-26 19:34:07 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-26T17:34:07.820384", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: tests/tty/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-26 19:34:07 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-26T17:34:07.820383", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: tests/tty/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-26 19:34:12 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-26T17:34:12.833866", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: tests/tty/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-26 19:34:12 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-26T17:34:12.833922", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: tests/tty/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-26 19:34:17 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-26 19:34:17 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-26 19:34:18 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-26 19:34:18.940305
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
Log configuration: logs/log.conf
"
"2014-04-26 19:34:18 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-26 19:34:19 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-26T17:34:19.770954", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Send incorrect message => <sg<r>C2-12<sc<s>08<db<ie0:13<tm>tp>93/mr<esr0/esr<007</i>tp><tp>c1<at>00<wts<c1><g.", "nonDstTimezone": "CET"}"
"2014-04-26 19:34:28 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-26T17:34:28.958901", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Reach timeout. Verify CurrentCost wire connection or wave range", "nonDstTimezone": "CET"}"
"2014-04-26 19:34:29 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-26T17:34:29.780787", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Send incorrect message => m>scC18v.9/r>db076/s>tm>03:6/ie<mr1.<tp>sno><sno>id>07d<ye1/ye<h>wts045/at>/h/ms>.", "nonDstTimezone": "CET"}"
"2014-04-26 19:34:29 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-26T17:34:29.792298", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Reach timeout. Verify CurrentCost wire connection or wave range", "nonDstTimezone": "CET"}"
"2014-04-26 19:34:38 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-26T17:34:38.971160", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Reach timeout. Verify CurrentCost wire connection or wave range", "nonDstTimezone": "CET"}"
"2014-04-26 19:34:39 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-26T17:34:39.798239", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Reach timeout. Verify CurrentCost wire connection or wave range", "nonDstTimezone": "CET"}"
"2014-04-26 19:34:39 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-26T17:34:39.810062", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Reach timeout. Verify CurrentCost wire connection or wave range", "nonDstTimezone": "CET"}"
"2014-04-26 19:34:48 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-26T17:34:48.983484", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Reach timeout. Verify CurrentCost wire connection or wave range", "nonDstTimezone": "CET"}"
"2014-04-26 19:34:49 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-26T17:34:49.811377", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Reach timeout. Verify CurrentCost wire connection or wave range", "nonDstTimezone": "CET"}"
"2014-04-26 19:34:49 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-26T17:34:49.830727", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Reach timeout. Verify CurrentCost wire connection or wave range", "nonDstTimezone": "CET"}"
"2014-04-26 19:34:59 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-26T17:34:59.001903", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Reach timeout. Verify CurrentCost wire connection or wave range", "nonDstTimezone": "CET"}"
"2014-04-26 19:34:59 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-26T17:34:59.830055", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Reach timeout. Verify CurrentCost wire connection or wave range", "nonDstTimezone": "CET"}"
"2014-04-26 19:34:59 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-26T17:34:59.849919", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Reach timeout. Verify CurrentCost wire connection or wave range", "nonDstTimezone": "CET"}"
"2014-04-26 19:35:09 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-26T17:35:09.016974", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Reach timeout. Verify CurrentCost wire connection or wave range", "nonDstTimezone": "CET"}"
"2014-04-26 19:35:48 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: EDzadminZE, password: pasZECZCordZE, host: localhost"
"2014-04-26 19:35:48 - messager.py - send - ERROR - It works!"
"2014-04-26 19:35:48 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-26T17:35:48.593502", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-26 19:35:48 - messager.py - __init__ - ERROR - Problem trying to connect to RabbitMQ with this configuration: username: admin, password: password, host: 192.168.5.56"
"2014-04-26 19:35:48 - messager.py - send - ERROR - It works!"
"2014-04-26 19:35:48 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-26T17:35:48.846283", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-26 19:35:48 - messager.py - send - ERROR - It works!"
"2014-04-26 19:35:48 - messager.py - send - ERROR - It works!"
"2014-04-26 19:35:48 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-26T17:35:48.926768", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-26 19:35:50 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-26 19:35:50.246822
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
Log configuration: logs/log.conf
"
"2014-04-26 19:35:50 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-26T17:35:50.247295", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-26 19:35:55 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-26 19:35:55.252050
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
Log configuration: logs/log.conf
"
"2014-04-26 19:35:58 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: admzfzein, password: paszeasword, host: localhost"
"2014-04-26 19:35:58 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-26T17:35:58.257989", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-26 19:36:00 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-26 19:36:00.257544
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
Log configuration: logs/log.conf
"
"2014-04-26 19:36:00 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-26T17:36:00.275660", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-26 19:36:01 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-26 19:36:01.339563
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
Log configuration: logs/log.conf
"
"2014-04-26 19:36:01 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-26 19:36:11 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-26T17:36:11.369994", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Reach timeout. Verify CurrentCost wire connection or wave range", "nonDstTimezone": "CET"}"
"2014-04-26 19:36:11 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-26 19:36:11.599238
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
Log configuration: logs/log.conf
"
"2014-04-26 19:36:11 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-26 19:36:14 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: TTY port tests/tty/currentcost disconnected."
"2014-04-26 19:36:14 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-26T17:36:14.425907", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: tests/tty/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-26 19:36:15 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-26 19:36:15.662243
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
Log configuration: logs/log.conf
"
"2014-04-26 19:36:15 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-26 19:36:16 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-26T17:36:16.498292", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Send incorrect message => <msg><src>ensor>0</sensor><id>00077</id><type>1</type><ch1><watts>00405</watts></ch1></msg>.", "nonDstTimezone": "CET"}"
"2014-04-26 19:36:18 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-26 19:36:18.730818
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
Log configuration: logs/log.conf
"
"2014-04-26 19:36:18 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-26 19:36:19 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-26T17:36:19.571207", "message": "<msg><src>CC128-v1.29</src><dsb>00786</dsb><time>00:31:36</time><tmpr>19.3</tmpr><sensor>0</sensor><id>00077</id><type>1</type><ch1><watts>00405</watts></ch1></msg>", "nonDstTimezone": "CET"}"
