"2014-04-24 21:33:24 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 21:33:24.339630
Variable name: rty
Site name: erty
TTY port: /dev/currentcost
"
"2014-04-24 21:33:24 - messager.py - send - ERROR - {"variableID": "rty", "dstTimezone": "CEST", "siteID": "erty", "date": "2014-04-24T19:33:24.340112", "message": "CurrentCost rty in erty: TTY connection problem: /dev/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-24 21:33:29 - messager.py - send - ERROR - {"variableID": "rty", "dstTimezone": "CEST", "siteID": "erty", "date": "2014-04-24T19:33:29.344742", "message": "CurrentCost rty in erty: TTY connection problem: /dev/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-24 21:33:34 - messager.py - send - ERROR - {"variableID": "rty", "dstTimezone": "CEST", "siteID": "erty", "date": "2014-04-24T19:33:34.345340", "message": "CurrentCost rty in erty: TTY connection problem: /dev/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-24 21:59:16 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 21:59:16.304549
Variable name: rtyu
Site name: rtyui
TTY port: /dev/currentcost
"
"2014-04-24 22:31:36 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: EDzadminZE, password: pasZECZCordZE, host: localhost"
"2014-04-24 22:31:36 - messager.py - send - ERROR - It works!"
"2014-04-24 22:31:36 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T20:31:36.963138", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-24 22:31:36 - messager.py - __init__ - ERROR - Problem trying to connect to RabbitMQ with this configuration: username: admin, password: password, host: 192.168.5.56"
"2014-04-24 22:31:36 - messager.py - send - ERROR - It works!"
"2014-04-24 22:31:36 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T20:31:36.986443", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-24 22:31:37 - messager.py - send - ERROR - It works!"
"2014-04-24 22:31:37 - messager.py - send - ERROR - It works!"
"2014-04-24 22:31:37 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T20:31:37.066060", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-24 22:31:38 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 22:31:38.299092
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-24 22:31:38 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T20:31:38.299863", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-24 22:31:43 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 22:31:43.327868
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-24 22:31:46 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: admzfzein, password: paszeasword, host: localhost"
"2014-04-24 22:31:46 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T20:31:46.332932", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-24 22:31:48 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 22:31:48.332964
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-24 22:31:48 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T20:31:48.351175", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-24 22:31:49 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 22:31:49.422112
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-24 22:31:49 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-24 22:31:59 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T20:31:59.450472", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Reach timeout. Verify CurrentCost wire connection or wave range", "nonDstTimezone": "CET"}"
"2014-04-24 22:31:59 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 22:31:59.664741
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-24 22:31:59 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-24 22:32:02 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: TTY port tests/tty/currentcost disconnected."
"2014-04-24 22:32:02 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T20:32:02.499472", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: tests/tty/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-24 22:32:03 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 22:32:03.741599
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-24 22:32:03 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-24 22:32:04 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T20:32:04.577757", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Send incorrect message => <msg><src>ensor>0</sensor><id>00077</id><type>1</type><ch1><watts>00405</watts></ch1></msg>.", "nonDstTimezone": "CET"}"
"2014-04-24 22:32:06 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 22:32:06.827119
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-24 22:32:06 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-24 22:32:07 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T20:32:07.654515", "message": "<msg><src>CC128-v1.29</src><dsb>00786</dsb><time>00:31:36</time><tmpr>19.3</tmpr><sensor>0</sensor><id>00077</id><type>1</type><ch1><watts>00405</watts></ch1></msg>", "nonDstTimezone": "CET"}"
"2014-04-24 22:34:43 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: EDzadminZE, password: pasZECZCordZE, host: localhost"
"2014-04-24 22:34:43 - messager.py - send - ERROR - It works!"
"2014-04-24 22:34:43 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T20:34:43.593191", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-24 22:34:43 - messager.py - __init__ - ERROR - Problem trying to connect to RabbitMQ with this configuration: username: admin, password: password, host: 192.168.5.56"
"2014-04-24 22:34:43 - messager.py - send - ERROR - It works!"
"2014-04-24 22:34:43 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T20:34:43.845788", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-24 22:34:43 - messager.py - send - ERROR - It works!"
"2014-04-24 22:34:43 - messager.py - send - ERROR - It works!"
"2014-04-24 22:34:43 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T20:34:43.923828", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-24 22:34:45 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 22:34:45.250926
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-24 22:34:45 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T20:34:45.251388", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-24 22:34:50 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 22:34:50.251333
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-24 22:34:53 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: admzfzein, password: paszeasword, host: localhost"
"2014-04-24 22:34:53 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T20:34:53.256698", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-24 22:34:55 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 22:34:55.255985
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-24 22:34:55 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T20:34:55.274243", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-24 22:34:56 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 22:34:56.315161
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-24 22:34:56 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-24 22:35:06 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T20:35:06.333623", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Reach timeout. Verify CurrentCost wire connection or wave range", "nonDstTimezone": "CET"}"
"2014-04-24 22:35:06 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 22:35:06.547935
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-24 22:35:06 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-24 22:35:09 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: TTY port tests/tty/currentcost disconnected."
"2014-04-24 22:35:09 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T20:35:09.382718", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: tests/tty/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-24 22:35:10 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 22:35:10.644258
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-24 22:35:10 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-24 22:35:11 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T20:35:11.463183", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Send incorrect message => <msg><src>ensor>0</sensor><id>00077</id><type>1</type><ch1><watts>00405</watts></ch1></msg>.", "nonDstTimezone": "CET"}"
"2014-04-24 22:35:13 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 22:35:13.726389
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-24 22:35:13 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-24 22:35:14 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T20:35:14.534935", "message": "<msg><src>CC128-v1.29</src><dsb>00786</dsb><time>00:31:36</time><tmpr>19.3</tmpr><sensor>0</sensor><id>00077</id><type>1</type><ch1><watts>00405</watts></ch1></msg>", "nonDstTimezone": "CET"}"
"2014-04-24 22:56:01 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: EDzadminZE, password: pasZECZCordZE, host: localhost"
"2014-04-24 22:56:01 - messager.py - send - ERROR - It works!"
"2014-04-24 22:56:01 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T20:56:01.527398", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-24 22:56:01 - messager.py - __init__ - ERROR - Problem trying to connect to RabbitMQ with this configuration: username: admin, password: password, host: 192.168.5.56"
"2014-04-24 22:56:01 - messager.py - send - ERROR - It works!"
"2014-04-24 22:56:01 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T20:56:01.780300", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-24 22:56:01 - messager.py - send - ERROR - It works!"
"2014-04-24 22:56:01 - messager.py - send - ERROR - It works!"
"2014-04-24 22:56:01 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T20:56:01.859238", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-24 22:56:03 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 22:56:03.303469
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-24 22:56:03 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T20:56:03.304198", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-24 22:56:08 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 22:56:08.341732
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-24 22:56:11 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: admzfzein, password: paszeasword, host: localhost"
"2014-04-24 22:56:11 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T20:56:11.346732", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-24 22:56:13 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 22:56:13.339893
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-24 22:56:13 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T20:56:13.358955", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-24 22:56:14 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 22:56:14.410423
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-24 22:56:14 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-24 22:56:24 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T20:56:24.429608", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Reach timeout. Verify CurrentCost wire connection or wave range", "nonDstTimezone": "CET"}"
"2014-04-24 22:56:24 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 22:56:24.650091
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-24 22:56:24 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-24 22:56:27 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: TTY port tests/tty/currentcost disconnected."
"2014-04-24 22:56:27 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T20:56:27.478147", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: tests/tty/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-24 22:56:28 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 22:56:28.728581
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-24 22:56:28 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-24 22:56:29 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T20:56:29.557981", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Send incorrect message => <msg><src>ensor>0</sensor><id>00077</id><type>1</type><ch1><watts>00405</watts></ch1></msg>.", "nonDstTimezone": "CET"}"
"2014-04-24 22:56:31 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 22:56:31.810248
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-24 22:56:31 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-24 22:56:32 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T20:56:32.632534", "message": "<msg><src>CC128-v1.29</src><dsb>00786</dsb><time>00:31:36</time><tmpr>19.3</tmpr><sensor>0</sensor><id>00077</id><type>1</type><ch1><watts>00405</watts></ch1></msg>", "nonDstTimezone": "CET"}"
"2014-04-24 23:29:12 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: EDzadminZE, password: pasZECZCordZE, host: localhost"
"2014-04-24 23:29:12 - messager.py - send - ERROR - It works!"
"2014-04-24 23:29:12 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T21:29:12.170263", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-24 23:29:12 - messager.py - __init__ - ERROR - Problem trying to connect to RabbitMQ with this configuration: username: admin, password: password, host: 192.168.5.56"
"2014-04-24 23:29:12 - messager.py - send - ERROR - It works!"
"2014-04-24 23:29:12 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T21:29:12.193909", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-24 23:29:12 - messager.py - send - ERROR - It works!"
"2014-04-24 23:29:12 - messager.py - send - ERROR - It works!"
"2014-04-24 23:29:12 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T21:29:12.274885", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-24 23:29:13 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 23:29:13.622503
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-24 23:29:13 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T21:29:13.623206", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-24 23:29:18 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 23:29:18.618688
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-24 23:29:21 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: admzfzein, password: paszeasword, host: localhost"
"2014-04-24 23:29:21 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T21:29:21.623785", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-24 23:29:23 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 23:29:23.646313
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-24 23:29:23 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T21:29:23.666285", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-24 23:29:24 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 23:29:24.697871
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-24 23:29:24 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-24 23:29:34 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T21:29:34.725899", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Reach timeout. Verify CurrentCost wire connection or wave range", "nonDstTimezone": "CET"}"
"2014-04-24 23:29:34 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 23:29:34.943486
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-24 23:29:34 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-24 23:29:37 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: TTY port tests/tty/currentcost disconnected."
"2014-04-24 23:29:37 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T21:29:37.776381", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: tests/tty/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-24 23:29:39 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 23:29:39.034995
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-24 23:29:39 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-24 23:29:39 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T21:29:39.847652", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Send incorrect message => <msg><src>ensor>0</sensor><id>00077</id><type>1</type><ch1><watts>00405</watts></ch1></msg>.", "nonDstTimezone": "CET"}"
"2014-04-24 23:29:42 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-24 23:29:42.087356
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-24 23:29:42 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-24 23:29:42 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T21:29:42.923996", "message": "<msg><src>CC128-v1.29</src><dsb>00786</dsb><time>00:31:36</time><tmpr>19.3</tmpr><sensor>0</sensor><id>00077</id><type>1</type><ch1><watts>00405</watts></ch1></msg>", "nonDstTimezone": "CET"}"
"2014-04-25 00:14:19 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: EDzadminZE, password: pasZECZCordZE, host: localhost"
"2014-04-25 00:14:19 - messager.py - send - ERROR - It works!"
"2014-04-25 00:14:19 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T22:14:19.814353", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 00:14:19 - messager.py - __init__ - ERROR - Problem trying to connect to RabbitMQ with this configuration: username: admin, password: password, host: 192.168.5.56"
"2014-04-25 00:14:19 - messager.py - send - ERROR - It works!"
"2014-04-25 00:14:19 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T22:14:19.837127", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 00:14:19 - messager.py - send - ERROR - It works!"
"2014-04-25 00:14:19 - messager.py - send - ERROR - It works!"
"2014-04-25 00:14:19 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T22:14:19.917000", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 00:16:52 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: EDzadminZE, password: pasZECZCordZE, host: localhost"
"2014-04-25 00:16:52 - messager.py - send - ERROR - It works!"
"2014-04-25 00:16:52 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T22:16:52.769753", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 00:16:53 - messager.py - __init__ - ERROR - Problem trying to connect to RabbitMQ with this configuration: username: admin, password: password, host: 192.168.5.56"
"2014-04-25 00:16:53 - messager.py - send - ERROR - It works!"
"2014-04-25 00:16:53 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T22:16:53.022675", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 00:16:53 - messager.py - send - ERROR - It works!"
"2014-04-25 00:16:53 - messager.py - send - ERROR - It works!"
"2014-04-25 00:16:53 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T22:16:53.102886", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 00:16:54 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 00:16:54.362495
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-25 00:16:54 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T22:16:54.362980", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 00:16:59 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 00:16:59.384685
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-25 00:17:02 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: admzfzein, password: paszeasword, host: localhost"
"2014-04-25 00:17:02 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T22:17:02.397716", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 00:17:04 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 00:17:04.401860
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-25 00:17:04 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T22:17:04.422713", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 00:17:05 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 00:17:05.543107
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-25 00:17:05 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-25 00:17:15 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T22:17:15.568927", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Reach timeout. Verify CurrentCost wire connection or wave range", "nonDstTimezone": "CET"}"
"2014-04-25 00:17:15 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 00:17:15.790578
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-25 00:17:15 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-25 00:17:18 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: TTY port tests/tty/currentcost disconnected."
"2014-04-25 00:17:18 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T22:17:18.619330", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: tests/tty/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 00:17:19 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 00:17:19.870392
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-25 00:17:19 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-25 00:17:20 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T22:17:20.700147", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Send incorrect message => <msg><src>ensor>0</sensor><id>00077</id><type>1</type><ch1><watts>00405</watts></ch1></msg>.", "nonDstTimezone": "CET"}"
"2014-04-25 00:17:22 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 00:17:22.962564
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-25 00:17:22 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-25 00:17:23 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T22:17:23.777324", "message": "<msg><src>CC128-v1.29</src><dsb>00786</dsb><time>00:31:36</time><tmpr>19.3</tmpr><sensor>0</sensor><id>00077</id><type>1</type><ch1><watts>00405</watts></ch1></msg>", "nonDstTimezone": "CET"}"
"2014-04-25 00:23:19 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: EDzadminZE, password: pasZECZCordZE, host: localhost"
"2014-04-25 00:23:19 - messager.py - send - ERROR - It works!"
"2014-04-25 00:23:19 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T22:23:19.462213", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 00:23:19 - messager.py - __init__ - ERROR - Problem trying to connect to RabbitMQ with this configuration: username: admin, password: password, host: 192.168.5.56"
"2014-04-25 00:23:19 - messager.py - send - ERROR - It works!"
"2014-04-25 00:23:19 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T22:23:19.485457", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 00:23:19 - messager.py - send - ERROR - It works!"
"2014-04-25 00:23:19 - messager.py - send - ERROR - It works!"
"2014-04-25 00:23:19 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T22:23:19.572171", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 00:23:20 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 00:23:20.848978
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-25 00:23:20 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T22:23:20.849606", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 00:23:25 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 00:23:25.862428
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-25 00:23:28 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: admzfzein, password: paszeasword, host: localhost"
"2014-04-25 00:23:28 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T22:23:28.867711", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 00:23:30 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 00:23:30.877642
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-25 00:23:30 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T22:23:30.897016", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 00:23:31 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 00:23:31.973684
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-25 00:23:31 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-25 00:23:42 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T22:23:42.002278", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Reach timeout. Verify CurrentCost wire connection or wave range", "nonDstTimezone": "CET"}"
"2014-04-25 00:23:42 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 00:23:42.332966
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-25 00:23:42 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-25 00:23:45 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: TTY port tests/tty/currentcost disconnected."
"2014-04-25 00:23:45 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T22:23:45.059696", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: tests/tty/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 00:23:46 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 00:23:46.323153
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-25 00:23:46 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-25 00:23:47 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T22:23:47.154057", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Send incorrect message => <msg><src>ensor>0</sensor><id>00077</id><type>1</type><ch1><watts>00405</watts></ch1></msg>.", "nonDstTimezone": "CET"}"
"2014-04-25 00:23:49 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 00:23:49.407716
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-25 00:23:49 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-25 00:23:50 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T22:23:50.240307", "message": "<msg><src>CC128-v1.29</src><dsb>00786</dsb><time>00:31:36</time><tmpr>19.3</tmpr><sensor>0</sensor><id>00077</id><type>1</type><ch1><watts>00405</watts></ch1></msg>", "nonDstTimezone": "CET"}"
"2014-04-25 00:38:57 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: EDzadminZE, password: pasZECZCordZE, host: localhost"
"2014-04-25 00:38:57 - messager.py - send - ERROR - It works!"
"2014-04-25 00:38:57 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T22:38:57.377433", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 00:38:57 - messager.py - __init__ - ERROR - Problem trying to connect to RabbitMQ with this configuration: username: admin, password: password, host: 192.168.5.56"
"2014-04-25 00:38:57 - messager.py - send - ERROR - It works!"
"2014-04-25 00:38:57 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T22:38:57.630102", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 00:38:57 - messager.py - send - ERROR - It works!"
"2014-04-25 00:38:57 - messager.py - send - ERROR - It works!"
"2014-04-25 00:38:57 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T22:38:57.708449", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 00:39:35 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: EDzadminZE, password: pasZECZCordZE, host: localhost"
"2014-04-25 00:39:35 - messager.py - send - ERROR - It works!"
"2014-04-25 00:39:35 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T22:39:35.949326", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 00:39:35 - messager.py - __init__ - ERROR - Problem trying to connect to RabbitMQ with this configuration: username: admin, password: password, host: 192.168.5.56"
"2014-04-25 00:39:35 - messager.py - send - ERROR - It works!"
"2014-04-25 00:39:35 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T22:39:35.972026", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 00:39:35 - messager.py - send - ERROR - It works!"
"2014-04-25 00:39:36 - messager.py - send - ERROR - It works!"
"2014-04-25 00:39:36 - messager.py - send - ERROR - {"variableID": "TEST_VAR", "dstTimezone": "CEST", "siteID": "TEST_SITE", "date": "2014-04-24T22:39:36.052342", "message": "It works!", "nonDstTimezone": "CET"}"
"2014-04-25 00:39:37 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 00:39:37.297085
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-25 00:39:37 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T22:39:37.297871", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 00:39:42 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 00:39:42.331104
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-25 00:39:45 - messager.py - __init__ - ERROR - Problem bad RabbitMQ credential with this configuration: username: admzfzein, password: paszeasword, host: localhost"
"2014-04-25 00:39:45 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T22:39:45.336933", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 00:39:47 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 00:39:47.334043
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: /dev/currentcost9876
"
"2014-04-25 00:39:47 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T22:39:47.352333", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: /dev/currentcost9876 is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 00:39:48 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 00:39:48.440541
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-25 00:39:48 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-25 00:39:58 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T22:39:58.465647", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Reach timeout. Verify CurrentCost wire connection or wave range", "nonDstTimezone": "CET"}"
"2014-04-25 00:39:58 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 00:39:58.681994
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-25 00:39:58 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-25 00:40:01 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: TTY port tests/tty/currentcost disconnected."
"2014-04-25 00:40:01 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T22:40:01.513522", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: TTY connection problem: tests/tty/currentcost is unreachable. Retry connection in 5 seconds.", "nonDstTimezone": "CET"}"
"2014-04-25 00:40:02 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 00:40:02.773058
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-25 00:40:02 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-25 00:40:03 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T22:40:03.592650", "message": "CurrentCost TEST_electric_meter in TEST_liogen_home: Send incorrect message => <msg><src>ensor>0</sensor><id>00077</id><type>1</type><ch1><watts>00405</watts></ch1></msg>.", "nonDstTimezone": "CET"}"
"2014-04-25 00:40:05 - utils.py - init_message - INFO - Starting current cost application
Current time: 2014-04-25 00:40:05.871592
Variable name: TEST_electric_meter
Site name: TEST_liogen_home
TTY port: tests/tty/currentcost
"
"2014-04-25 00:40:05 - phase-currentcost - main - INFO - CurrentCost TEST_electric_meter in TEST_liogen_home: Success connection to tests/tty/currentcost."
"2014-04-25 00:40:06 - messager.py - send - ERROR - {"variableID": "TEST_electric_meter", "dstTimezone": "CEST", "siteID": "TEST_liogen_home", "date": "2014-04-24T22:40:06.672462", "message": "<msg><src>CC128-v1.29</src><dsb>00786</dsb><time>00:31:36</time><tmpr>19.3</tmpr><sensor>0</sensor><id>00077</id><type>1</type><ch1><watts>00405</watts></ch1></msg>", "nonDstTimezone": "CET"}"
